# Generated by Django 4.1.1 on 2022-12-16 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurre_website', '0003_rename_user_id_review_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewRate',
        ),
        migrations.RenameField(
            model_name='reviewrate',
            old_name='user',
            new_name='user_id',
        ),
    ]
